### PR TITLE
Seq.seq(Optional<? extends T>...) implementation

### PR DESCRIPTION
**Pull request by earlzero**
Implementation for #213.

### CODE REVIEW

**Comment by amaembo** [comment]
At least I'd suggest to replace `Stream.empty()` with `null` which is allowed for `flatMap`, means the same and works notably faster. But it would be even faster to use `.filter(Optional::isPresent).map(Optional::get)` as no intermediate streams are created here.

**Comment by tkroman** [comment]
@earlzero, would you consider adding an instance method for this as well (if there's none)?
Something that works like this: ` flattenOptionals: Seq<Optional<? extends T>> -> Seq<? extends T> `

**Comment by lukaseder** [comment]
> At least I'd suggest to replace Stream.empty() with null

o_O, how could that implementation detail possibly leak into the public API?? Oh my... `Stream.concat()` should allow null arguments too, then?

**Comment by lukaseder** [comment]
@earlzero : Thank you very much for your implementation suggestion. The reason why this hasn't been implemented yet is because of nasty warnings at the call-site about heap pollution. I'm not 100% convinced yet, that this should really be added.

**Comment by earlzero** [comment]
@lukaseder don't mention. Anyway it was pretty  straightforward one :).

**Comment by tkroman** [comment]
@lukaseder But this would be sooo useful! You should try to convince yourself that this is needed :D

**Comment by lukaseder** [comment]
@earlzero @tkroman We're not in a hurry to make a decision. I just wanted to state why this hasn't been implemented yet. :)

**Comment by earlzero** [comment]
@lukaseder I checked why heap pollution may occur (https://docs.oracle.com/javase/tutorial/java/generics/nonReifiableVarargsType.html#vulnerabilities). I don't think it's applicable to this case (we don't rely on features of the type T, we don't try to change optionals array). I can use `SafeVarargs` to prevent this message from appearing, if I convinced you enough :).

@amaembo filter/map solution will definitely work faster, but I don't think this particular place is performance critical.

**Comment by lukaseder** [comment]
@earlzero I know that heap pollution cannot occur in this case, but there's still a nasty warning at the client side. Unfortunately, the `@SafeVarargs` annotation cannot be placed on interface methods...

**Comment by earlzero** [comment]
@lukaseder SafeVarargs can't be put on non-final or non-static methods, but seq here is static, so we can use it.

**Comment by lukaseder** [comment]
My bad, I overlooked that detail. I'll merge your suggestion, apply the fix suggested by @amaembo, and add `@SafeVarargs`

**Comment by lukaseder** [comment]
Thanks again!

**Comment by lukaseder** [comment]
In fact, why not just get rid of `flatMap` entirely and do this instead:

```java
    static <T> Seq<T> seq(Optional<? extends T>... optionals) {
        return of(optionals).filter(Optional::isPresent).map(Optional::get);
    }
```

**Comment by amaembo** [comment]
That's exactly what I suggested!

**Comment by lukaseder** [comment]
Oh, I TL;DR your reply, I suspect :)

**Pull request merged**
