### PR TITLE
Non-terminal Seq#grouped implementation

### PR DESCRIPTION
**Pull request by tkroman**
As discussed in #105.

### CODE REVIEW

**Comment by lukaseder** [comment]
Thanks a lot for your contribution. I'll merge and comment / fix afterwards

**Comment by lukaseder** [comment]
At first sight, this looks really great! Thanks again for this contribution. I'll review this again next week and do a write up on the jOOQ blog. Do you have a personal / company website you'd like me to link to when referencing your work?

**Comment by tkroman** [comment]
Awesome! Looking forward to that review. 

We do use jOOL in our backed at https://wri.tt and it really helps to cut the boilerplate to a minimum, so yeah, you are welcome to mention.

**Comment by lukaseder** [comment]
All tests pass now. Would love to hear your comments on the current implementation

**Comment by tkroman** [comment]
Wow! Looks like I stopped receiving notifications after the PR was accepted. Shame on me and thank you for correcting my mistake!

**Comment by lukaseder** [comment]
> I'll still try to think if there exists any data structure that will allow to eliminate the duplication.

Yes, I was thinking the same thing at first. A more sophisticated data structure than `LinkedHashMap` might provide access to an `Iterator` that still works when the `LinkedHashMap` is modified...

**Pull request merged**
