### PR TITLE
Add Seq#zipWithIndex(BiFunction)

### PR DESCRIPTION
**Pull request by Xaerxess**
I wanted to use `Seq#zipWithIndex(BiFunction)`, but unfortunately it wasn't available, so here's implementation. Instead writing:

    Seq.of("a", "b", "c")
            .zipWithIndex()
            .map(t -> t.map((s, i) -> i + ":" + s))
            .forEach(System.out::println);

one can write:

    Seq.of("a", "b", "c")
            .zipWithIndex((s, i) -> i + ":" + s))
            .forEach(System.out::println);

(and no `Tuple2` object is created.)

### CODE REVIEW

**Comment by lukaseder** [comment]
Nice idea, thank you very much for the suggestion!

**Comment by Xaerxess** [comment]
Note that with `Seq2` (PR #172) it'd be cleaner even without this PR (although tuple objects still would be created).

**Comment by lukaseder** [comment]
I don't think this is unclean. And this `Seq2` thing is still giving me headaches :)

**Comment by Xaerxess** [comment]
Just sayin' :) And thanks for quick merge!

**Pull request merged**
