### PR TITLE
Moved Async and SameExecutorCompletionStage to org.jooq.lambda

### PR DESCRIPTION
**Pull request by billoneil**
resolves https://github.com/jOOQ/jOOL/issues/287

### CODE REVIEW

**Comment by lukaseder** [comment]
Thanks a lot!

**Comment by lukaseder** [comment]
Hmm, looks like some tests fail nondeterministically: 
https://travis-ci.org/jOOQ/jOOL/builds/203172319#L896

They didn't fail on my machine

**Comment by billoneil** [comment]
Looking into it now.

**Comment by billoneil** [comment]
I think its possible for the `countdown` to complete

It looks like its possible to return before the count is incremented here. I can add a join before every assert to assure the `CompletionStage` is finished executing.
```java
counter.accumulateAndGet(1, (left, right) -> {
    delegate.execute(command);
    return left + right;
});
```

**Pull request merged**
