### PR TITLE
Implement Agg.percentRankBy() in terms of Agg.rankBy()

### PR DESCRIPTION
**Pull request by Xaerxess**
As per [comment](https://github.com/jOOQ/jOOL/issues/254#issuecomment-241574426) in PR #254 here comes `percentRankBy` implementation using `Tuple.collectors` and `rankBy`.

### CODE REVIEW

**Comment by amaembo** [comment]
What about division by zero?

**Comment by Xaerxess** [comment]
Should not occur - `Optional` would be empty (from `rankBy`) and map should
not execute.

23 sie 2016 19:35 "Tagir Valeev" <notifications@github.com> napisał(a):

**Comment by amaembo** [comment]
Looks like you're right. Ok then.

**Comment by lukaseder** [comment]
Thank you very much!

**Pull request merged**
