### PR TITLE
Added Curry methods to Functions

### PR DESCRIPTION
**Pull request by LordBlackhole**
As per: #87 

Added curry() methods to all Functions, allowing them to be partially applied and return a new function that accepts the remaining arguments.

### CODE REVIEW

**Comment by lukaseder** [comment]
Nice, thank you. Are you contributing this under the terms of the [Apache License 2.0](http://www.apache.org/licenses/LICENSE-2.0)?

**Comment by danieldietrich** [comment]
'Morning guys,
I'm not a licensing expert but by contributing to a project which is under Apachy 2.0 license, this should be clear, isn't it?

**Comment by lukaseder** [comment]
Says who? Some random lawyer at Red Hat? :-)

**Comment by danieldietrich** [comment]
Hehe, don't know :-) Read this https://www.apache.org/licenses/LICENSE-2.0 and interpreted def. of Contribution + Grant of * (2. and 3.)...

**Comment by lukaseder** [comment]
Eh, actually, it's here:

> 5. Submission of Contributions. Unless You explicitly state otherwise, any Contribution intentionally submitted for inclusion in the Work by You to the Licensor shall be under the terms and conditions of this License, without any additional terms or conditions. Notwithstanding the above, nothing herein shall supersede or modify the terms of any separate license agreement you may have executed with Licensor regarding such Contributions.

Interesting, I haven't noticed this, so far. Thanks!

**Comment by danieldietrich** [comment]
Interesting is the last sentence

> Notwithstanding the above, nothing herein shall supersede or modify the terms of any separate license agreement you may have executed with Licensor regarding such Contributions.

Does this has an impact to a dual license? I think not because we speak about contribution and not usage.

**Comment by lukaseder** [comment]
> Does this has an impact to a dual license?

What kind of impact were you thinking of?

**Comment by danieldietrich** [comment]
No, this was a 'Denkfehler'.

**Comment by LordBlackhole** [comment]
@lukaseder Oh yes, I wrote that lift method in a spur-of the moment to get the method into a function, and then immediately realized how useful it could be everywhere else. 

I saw how you mentioned in #54 having a single point of entry for the DSL. Is there a place for that yet? How about a "Functions" class next to Function0-8? Could be a dump-all for all Function-related static helper methods. 

The thing about lift() is that it works great unless the method you want to lift is overloaded. Then you must provide the generics, which is tedious. 

Another thing it can't do is pick up a method with a return type of void, as those aren't functions. Which got me thinking about Consumers, and I realized there is nothing preventing making Function1 and Function2 extend Consumer and BiConsumer, they'd just throw away their results. 

Might not be that terribly useful, but I've been using the Stream.peak() for logging to help debug them, and because those methods return void you can't use them with any of the Functions without wrapping them manually. 

Oh, and yes I respect the license, I thought that was implied.

**Comment by lukaseder** [comment]
>  saw how you mentioned in #54 having a single point of entry for the DSL. Is there a place for that yet?

No.

> How about a "Functions" class next to Function0-8? Could be a dump-all for all Function-related static helper methods.

I know that many people like to group "global functions". I prefer to have only a single class where all static methods / "global functions" go, so people can just static-import `com.example.SingleClass.*` to have all the awesome tools on the classpath. It sucks when you have to find a method in dozens of utility classes.

> Another thing it can't do is pick up a method with a return type of void, as those aren't functions. Which got me thinking about Consumers, and I realized there is nothing preventing making Function1 and Function2 extend Consumer and BiConsumer, they'd just throw away their results.

Could you show an example? I personally don't think it's a good idea to have those types extend each other... That seems to be calling for trouble later on.

> Oh, and yes I respect the license, I thought that was implied.

Yes, it is. I stood corrected.

**Comment by LordBlackhole** [comment]
All I was thinking was 

```java
public class Function1<T1, R> extends Function<T1, R>, Consumer<T1> {

    @Override
    default accept(T1 v1) {
        apply(v1);
    }

...
}
```

Although I do see what you mean. Some way of lifting a void method into a function so we  can use the curry and other methods might be useful though. Now I truly understand why Scala uses Unit instead of void. Another option would be to have Consumer0 - 8, but I think that's far too much effort. I don't know, it might not be that necessary. Just having lift() methods that take Consumers and turn them info Functions would work too, though there isn't an obvious return type.

**Comment by lukaseder** [comment]
I see, yes that's what I thought you meant. But I have a very uneasy feeling with this. I'm sure this will cause compile-time ambiguities somewhere down the line.

> Now I truly understand why Scala uses Unit instead of void.

Yes. `void` is such a horrible wart in the Java type system.

> Another option would be to have Consumer0 - 8, but I think that's far too much effort

No, I think that would certainly make sense, eventually...

> Just having lift() methods that take Consumers and turn them info Functions would work too

Yep. In the meantime, this issue seems to have been resolved: http://stackoverflow.com/q/23430854/521799, so you're safe to do that.

**Pull request merged**
