### PR TITLE
OSGi-fied the complete Library

### PR DESCRIPTION
**Pull request by amitjoy**
Making use of this library in Dynamic Execution Environment like OSGi

### CODE REVIEW

**Comment by amitjoy** [comment]
The error log seems very disappointing as it failed during test run as it couldn't locate the test classes. Would anyone please do let me know what happened in Travis as it ran successfully locally?

**Comment by lukaseder** [comment]
Thank you very much for your contribution. I certainly think this is a very good idea.

May I ask you please to not reformat the pom.xml file in the same commit? It will be easier to track changes in the future, when cosmetic changes are separated from semantic ones.

Don't worry about Travis. For some reason, Travis is still using Java 1.8.0_31, which suffers from tons of compiler bugs...

**Comment by amitjoy** [comment]
As you suggested, I have committed the changes again. Please have a look at it.

**Comment by lukaseder** [comment]
Thank you very much. May I ask what the additional `org.osgi.core` dependency is for?

**Comment by amitjoy** [comment]
I forgot to remove the dependency previously. Now I have committed again the necessary changes.

**Comment by lukaseder** [comment]
Thank you very much for your help!

**Comment by amitjoy** [comment]
Happy to help!


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jooq/jool/133)

**Pull request merged**
